.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. shard_qt test_shard_qt
clean: FORCE
	$(MAKE) -C .. shard_qt_clean test_shard_qt_clean
check: FORCE
	$(MAKE) -C .. test_shard_qt_check
shard-qt shard-qt.exe: FORCE
	 $(MAKE) -C .. shard_qt
